// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
export {}
