// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Advertise: typeof import('./src/components/bottom/Advertise.vue')['default']
    BtnMagic: typeof import('./src/components/littleTool/BtnMagic.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CardMini: typeof import('./src/components/Card/CardMini.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ImgZoom: typeof import('./src/components/ImgZoom/ImgZoom.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavHeader_admin: typeof import('./src/components/NavHeader_admin.vue')['default']
    NavHeader_PC: typeof import('./src/components/NavHeader_PC.vue')['default']
    Page1: typeof import('./src/components/homepage/Page1.vue')['default']
    Page2: typeof import('./src/components/homepage/Page2.vue')['default']
    Page3: typeof import('./src/components/homepage/Page3.vue')['default']
    PartPrize: typeof import('./src/components/admin/new-competition/PartPrize.vue')['default']
    Pop: typeof import('./src/components/Pop/Pop.vue')['default']
    Protocol: typeof import('./src/components/littleTool/Protocol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeasonBtn: typeof import('./src/components/SeasonBtn.vue')['default']
    TabMagic: typeof import('./src/components/TabMagic/TabMagic.vue')['default']
  }
}

export {}
